build:
		g++ main.cpp -o tema1 -lpthread

clean:
		rm -f tema1 a.txt b.txt c.txt d.txt e.txt f.txt g.txt h.txt i.txt j.txt k.txt l.txt m.txt n.txt o.txt p.txt q.txt r.txt s.txt t.txt u.txt v.txt w.txt x.txt y.txt z.txt

# replace for build: g++ main.cpp -o tema1 -Wall -Werror
